### PR TITLE
Fix dark theme for new Ecosia search result

### PR DESCRIPTION
**Pull request by muhfajar**
Make little changes based on working CSS injection for the search result

From this
image

To this
image

### CODE REVIEW

**Review by aidanhorton — CHANGES_REQUESTED** [review]
Hiya!

I really appreciate you putting in the work to do this, unfortunately there is a problem.
When Ecosia makes a big change like this, they usually roll it out to a small number of users at a time (you're one of the lucky ones!) - but me and most other people are stuck on the old-style search page!
I ran this code in the PR locally and this is what happens for my search results:
image

The solution to this is to simply add all of your changes to the bottom of the file, keeping the existing CSS style, and then together they should fix both styles of search pages :)

I can make the change if you like, just let me know!

**Comment by muhfajar** [comment]
Ahh, I see, that's a good idea, keep the old one and add new styling on the bottom, it's ok from me if you want to make the change :)

**Comment by aidanhorton** [comment]
@muhfajar apologies this took so long!



I made the changes necessary - I added the initial style back at the top, and then I had to make 2 style changes in order to make the initial theme compatible with yours - otherwise the following issues would occur:
- The 'Maps' and 'More' dropdown buttons in the navbar would have square borders around them and also have a lighter-background colour.
- The search bar colour would 'leak' over the border (basically the border would not be visible on the bottom-half of the search bar).
- The top-right dropdown hamburger menu had the same issue as the 'Maps' and 'More' buttons where it had a square border around it.


In order to do this I had to remove the following lines from your style:
`input {
	background: #292929 !important;
    color: var(--text) !important;
}

.dropdown {
    background: var(--form) !important;
    border: 1px solid;
}`

Obviously this is likely to make some parts of your theme not work, so this may require a tiny bit of back and forth in order to get this working for both ends without conflicts.

Being unable to verify if it works for the new-style search page on my end, if you get the chance to test this out, and let me know if it works or not, we can roll this out onto the extension asap :)

**Review by aidanhorton — APPROVED** [review]
Code-wise this all looks great - if this works without a hitch on your end with the changes I made then we can merge this in straight away.

If more changes are needed to fix it on your end from the changes that I made, then that's no problem, we'll get that fixed, just ignore the approval in that case.

**Comment by muhfajar** [comment]
@aidanhorton sorry for took too long for testing from my side

based on the latest changes from your feedback, after deleting for input and dropdown style, here is the result from my  Ecosia version

image

I make a little change to search-form and main-nav-menu class, please take a look at your Ecosia version

**Comment by aidanhorton** [comment]
Thanks for testing it out @muhfajar !

Sorry for all the back and forth, still one tiny issue with the styling on my end, see below:
image

I got a 2 star review on the Firefox extension because of this issue - so I really hope the fix I pushed doesn't mess up anything on your end, as it fixes the search bar issue for me.

Worst case scenario if it breaks it on your end, then we'll merge it in at your previous commit.

I'm going to merge this in, in around 2 days to avoid any further bad reviews.
Apologies for all the back-and-forth again. If you could give it a quick test it would save me a lot of trouble, but no worries if you don't have the time.

**Comment by aidanhorton** [comment]
I've committed this PR to master now as it is, so any further changes we'll open another PR for :)

**Comment by aidanhorton** [comment]
This fix has been uploaded to both respective extension stores - expect to see it auto-update in both browsers in the next day or so :)

**Pull request merged**
