### PR TITLE
Separate CSS from JS

### PR DESCRIPTION
**Pull request by OppnedKatt**
In the README.md, there is a line about separating the CSS from the JS to make the code more maintainable. Here you go. Removed one class in the style-tag from popup.html as I forgot to remove it. 

There is a problem where the site flashes for a very brief moment, before loading in the dark colours. I assume it's because it's getting the CSS-file, but it's taking a bit too long. Don't really know what there is to do about that, but the popup.css and newtab.css should not meet this issue. I would totally get dropping this one because of this if you can't fix it, but I'll leave it here for now. The blinking should only appear when searching for the first time in a tab. So searching multiple times in the same tab shouldn't end up with blinking.

### CODE REVIEW

**Comment by OppnedKatt** [comment]
If this were to go through, should the CSS-files maybe be moved to a different folder from the JS-files? Something like "injection-styles" or something?

**Comment by aidanhorton** [comment]
This is great stuff! I'll check it out soon properly, but yeah I tried to do something similar when I first started - but quickly decided that I hated JS so therefore gave up 😂
So good work getting this sorted!
Different folder could be a good idea TBF, either way is fine by me but a folder is probably preferred!

**Comment by OppnedKatt** [comment]
A new PR about some new-tab-stuff will introduce a conflict with this PR in the CSS of the newtab.html as it introduces some new and changed styling.

**Comment by aidanhorton** [comment]
I won't push these changes to the Chrome or FireFox web store right now - I'll do some more testing and checking, but in the interest of improving the codebase ASAP, we'll merge this in now! :) Great work again!

**Pull request merged**
