### PR TITLE
Features and fixes

### LINKED ISSUE #47: White flash upon page load Chrome
In Chrome I'm getting a white flash upon page load, or typing a new search term, or anything really that triggers the code to be re-run!
It's just a small white flash, but it's annoying and slightly concerning!

The number of active users on the extension has gone down by a fair bit recently too, so maybe the two are correlated? I think this would likely be something around the fixes done earlier to make the page defualt to dark mode.

I don't believe this is an issue in Firefox.

### LINKED ISSUE #48: Extension size is incorrect
In my haste to push an update to fix https://github.com/aidanhorton/ecosia-darkmode-extensions/issues/46, I accidentally broke the extension window size a bit - it's nothing catastrophic, just looks a bit bad as it cuts off the clear button at the bottom!

image

### PR DESCRIPTION
**Pull request by OppnedKatt**
**Goals**:
- Add follow system preference option: **Done**
- Add search suggestions on new tab page (#4): **Not fixed styling**
- Fix #47 as is seems like it still occurs: **Being investigated**
- Fixed #48 by making the height auto: **Done**

I did some tidying of a bit of popup.js, but I feel like some more could be done. 

~~I did some testing a while ago, and it seems that adding an option for different "themes", would be somewhat simple with the new way the CSS is handled. But I haven't added this to the goal as I'm not sure if this is something you would want.~~

When testing the follow system preference option on my slower laptop, the white flashing occurred every time I searched, but I were unable to analyse it as it worked as it should when going one step at a time in the source view. Maybe it has to do with the loading of the CSS-file being too slow? Maybe there is a way to detect that a CSS-file has finished loading.

### CODE REVIEW

**Comment by OppnedKatt** [comment]
The styling is quite broken and not looked at. I didn't add all the datasets, so maybe you styled it with that if you took Ecosia's styling, that would be a big reason for why it's so broken. Maybe you would like fixing that part 😁. 

bilde


Here is Ecosia's as a reference: 

bilde

**Comment by aidanhorton** [comment]
Amazing work! Great PR :)

For the theme stuff, lets leave that out of this one for now, but as long as it's done tastefully and it doesn't take up too much of the extension popup, then there's no reason we can't do it for the next PR or in future!

I can investigate the newtab page for sure! Pretty sure I took Ecosias page, but then added a little bit of my own tweaks to it, so yeah it's not gonna be an exact match unfortunately 😄 

And yeah the white flash is interesting, I too continue to see it with slower PCs - although I haven't tried it with the latest update to the extension (with the black page default fix). Weird one!

Great PR work! In the next few days I'll review what you've got so far and fix the newtab, and then just open the PR when you think it's ready to go in and I'll do a final look over :)

**Comment by OppnedKatt** [comment]
I feel like the outcome of the options may be a bit hard to predict for the end-user now (as you can have both follow system and time-based enabled at the same time). What if turning on follow system would automatically turn off time-based, and such. Having it be like that, we could also then assume that only one is turned on at a given time, resulting in logic which would make it easier to add or manage things. It could just check if one thing is enabled, do things which doesn't follow how other things would do it, instead of having to check every option before doing anything, as some things has to be suppressed anyway. Do you think this should be made into a thing?

**Comment by aidanhorton** [comment]
Just checking back on my Git projects - looks like Ecosia now has a built in dark mode!

Thanks for the help developing this, its been so valuable! And apologies for my slow reply speeds, but we've finally got the result we were looking for 😄

**Pull request closed without merging**
