### PR TITLE
Added a feature to have Darkmode be time based, and fixed a few bugs. 

### PR DESCRIPTION
**Pull request by OppnedKatt**
Redid the popup with settings to hopefully make it easier to add more settings in the future. The settings are currently all on the left side, but I have left a comment next to the specific CSS-property which needs to be changed in order to have it be centred as the previous popup-page had. Also left a note about the size of the popup. 

For the feature being mentioned further down, I made a few changes to all the JavaScript files in order to make adding more options a bit easier maybe, idk. 

Added a feature to have Darkmode be time based (Issue#1). The time of when the Darkmode turns off and on again is changeable in the settings. Pages checks the time every minute and checks if the settings are right for it do change anything. Typing in the time of it turning on and off is a bit weird, so that may need to be redone at some point. 

Fixed a bug where the sidebar on search had a border around it (looked similar to a recent bug fixed about advertisements having a border around them). Also fixed a bug where news and videos have a white background while loading. Also fixed the bug regarding the search-suggestions being white while hovering over them and typing in the search field (Issue#20). Also fixed a bunch of other bugs that I at this point won't bother writing up here. 

There is a python program included I think. I made it to make zipping the files easier when I tested the extention on Firefox, but you could just discard it (or whatever you want to call it), as I have a copy of it, unless you want it for some reason. Wasn't really intended to be included in the PR, but you could just keep it if you want to. 

Changed one letter in the README.md.

### CODE REVIEW

**Comment by OppnedKatt** [comment]
There are some other small bugs with some pages, but I'm tired of looking at them, and they aren't relevant to the original purpose of this Pull request, so I'll stop for now. Have a lot of other things to work on.

**Comment by aidanhorton** [comment]
Thanks very much! I'll check this out over the next few days - great work! And apologies for the terrible codebase 😅

**Comment by aidanhorton** [comment]
And yeah don't worry about small page bugs. If you wanted to, just keep a list of them and report them all as 1 big issue if you want me to fix them! :)

**Comment by OppnedKatt** [comment]
If it works it works. Insert x "Does the code work? Yes. Then don't touch it"-meme

**Comment by OppnedKatt** [comment]
The code I originally wrote was waaaaaaay worse then any of the earlier code anyways

**Comment by aidanhorton** [comment]
Sorry I feel awful for leaving this so long - just so snowed under by work at the moment that I rarely feel like programming outside of work time. I should get to this sometime in the next 2 weeks :)

**Comment by OppnedKatt** [comment]
It's fine. For all I care, take the time you need. Don't force yourself. :)

**Comment by OppnedKatt** [comment]
I have now been made aware of the existence of a time HTML-input-type. It would be much easier to use, and would reduce the code by a bit I think. I could try to fix it now, or I could include it as a thing I was planing to do after the PR has been fully reviewed and such. What do you think?

**Comment by aidanhorton** [comment]
> I have now been made aware of the existence of a time HTML-input-type. It would be much easier to use, and would reduce the code by a bit I think. I could try to fix it now, or I could include it as a thing I was planing to do after the PR has been fully reviewed and such. What do you think?

Hmmmm I would think that if it's one of the few major interaction points of the extension, it would be best to do it proper, mainly to avoid bugs - but I can always investigate if you like! I've set a calendar event to review this PR in the next few days :)

**Comment by OppnedKatt** [comment]
Well, I don't have time to fix it before the weekend. So do with that as you want.

**Comment by OppnedKatt** [comment]
It would only affect the popup.js & popup.html files though, so if you aren't going to go through them all in one go, then you could have them be the last ones you go through for example, but idk.

**Comment by OppnedKatt** [comment]
I actuallt got a working version of it during the break i an class, so I finish it up later today maybe. Shouldn't take that long.

**Comment by OppnedKatt** [comment]
There you go

**Comment by aidanhorton** [comment]
Checking this now! I'm impressed, this seems like a really good change - wish I had gotten to it sooner!
I found 1 issue with the lightmode not triggering if you play around with the settings, so I'm just having a fiddle to fix that - but apart from that, we should be able to get this in today!

**Comment by aidanhorton** [comment]
@OppnedKatt So I've checked this out, done a bit of testing too. With the changes I added above, I can't see any issues with this now, this is a really good feature and a great addition! Great work :)
If you're happy, I'll merge this in at the end of today, and it should be uploaded to the relevant app stores today too!

**Comment by aidanhorton** [comment]
Just noticed the little ZIP file utility too - love it too! :)

**Pull request merged**
