### PR TITLE
Fix various styling issues and other tweaks

### PR DESCRIPTION
**Pull request by aidanhorton**
Here's a new PR since I closed the previous one quite quickly in order to get the release out.
Any styling issues, report them here so we can resolve them in a hotfix update, and if there's any updates anyone wants to do, feel free to make them here for the next update :)

### CODE REVIEW

**Comment by aidanhorton** [comment]
Also found a bug where it now flashes in dark mode on page load when dark mode is disabled - any ideas on this? I assume this is relating to the fix for the flashing white on page load occasionally.

**Comment by OppnedKatt** [comment]
I have no idea on what's up with the last commit, but sure. I assume you want to make more changes to README.md

**Comment by aidanhorton** [comment]
> They seem to like using images with white on these info-pages, so having them be styled normally may be the best option.
Yeah I think you might be right. I'll investigate this a little bit, but will likely remove the dark mode for the info page. Means less permissions too in that case!

> Not 100% sure on what you are referring to here.
Oh I'm referring to me constantly changing the location of the manifest files & build locations etc so that the build file has to keep being changed - my bad 😄 

> I assume it's because of the background being applied before anything has loaded at all. It's later removed. The solution wasn't really that thought through as something should be done about the JS being repeated way too much, so I just threw together that somewhat fast since it's probably going to be changed on later anyways.
Yeah the JS repeating is becoming more of an issue isn't it! Okay that's fine - I'll raise a bug report for it, but for now I'm happy that this is better than flashing in white :)

**Comment by aidanhorton** [comment]
PS I've made a bunch more styling changes, and started to redo the newtab page in the new Ecosia style - it's taking a touch longer than expected but I'm getting there!

**Comment by OppnedKatt** [comment]
> Oh I'm referring to me constantly changing the location of the manifest files & build locations etc so that the build file has to keep being changed - my bad 😄

No worries. It doesn't take long changing it. And recently I made it even easier to change it and add new browsers.

**Comment by aidanhorton** [comment]
Newtab page should be finished now! The page should switch between light and dark mode depending on your setting, and it should be very similar to the official Ecosia newtab page!
If anyone else wants to take a look at it before it goes in to double-check it, that would be fab - and when we're happy with it, I'll merge this change in!

Things missing are:
- Search suggestions
- Tree counter

**Comment by aidanhorton** [comment]
Think this is unrelated, but I kept getting this error while debugging and opening newtabs.
image

**Comment by OppnedKatt** [comment]
Maybe some changes would be nice for when the window is small?
bilde

**Comment by aidanhorton** [comment]
Great! Thanks for the fix - and good feedback too! I think I'll raise a PBI for those 2 small things you mentioned, but I think this is pretty much good enough to go in! 😄

**Pull request merged**
