### PR TITLE
Fixed bugs, added some enhancements to the newtab page, and fixed an issue which broke the extention on chrome

### PR DESCRIPTION
**Pull request by OppnedKatt**
Fixed some small bugs, and made some more elements follow how Ecosia styles them a bit. 

Took care of #5 and #22.

Made a button on the pop-up that allows you to reset the removed most visited sites. As talked about in #10. 

Fixed the issue (#28) of Chrome not getting any styling except for on new tab because of #25. 

Includes a python-file for testing all supported sites on all supported browsers.

### CODE REVIEW

**Comment by aidanhorton** [comment]
Fab stuff! I'll check this out again as soon as I can and double check all the code :)

**Comment by aidanhorton** [comment]
Just did some tiny fixing up of the styling on the popup (because it looked like this for me!):
image

And also while I was at it I fixed 1 or 2 of the styling issues I found the other day - but apart from that, this seems like a fab change!

1 thing that I have thought of:
- Newtab page isn't active for FireFox, so this setting is redundant.

So what we should do for the above is probably one of the following options:
- Leave the setting there even though FireFox doesn't have a newtab page
- Make the reset button reset all settings in the app (if dark mode is on, light-mode times and most-visited sites)
- Hide the setting on FireFox.

Thoughts?

**Comment by OppnedKatt** [comment]
I had an idea for how the label could be redone, but I have forgotten about what it was. I have a general idea, but will see if I can remember it.

**Comment by OppnedKatt** [comment]
But what is your thought on having CSS handle the drop down on the new-tab-page as it makes tabbing to it open it?

**Comment by aidanhorton** [comment]
> But what is your thought on having CSS handle the drop down on the new-tab-page as it makes tabbing to it open it?

Not entirely sure, as with a toggle-button, you'd expect it to toggle-off when you press it again. With the button now, you have to click off the dropdown to close it - you can't reclick the button, which differs to how the Ecosia button does it. Not a huge issue as the button is rarely used, so I'm easy either way :)

**Comment by OppnedKatt** [comment]
I forgot about clicking it again xD
I think reverting it may be best then. Will look at it later if you don't fix it first. I have some stuff to do first.

**Comment by OppnedKatt** [comment]
I gave making it look a bit better an attempt. What do you think about the change?

**Comment by OppnedKatt** [comment]
You mentioned earlier the possibility of having a reset-button for all settings on the extension. I think that could be quite easy to add. So I could add that as well if you want to.

**Comment by aidanhorton** [comment]
Sorry I clicked on this notification the day you posted the update, but then forgot to revisit this - so only just found this! Will take a look over the next few days and see if this is all good! Thanks again :)

**Comment by OppnedKatt** [comment]
I changed a comment in the js-files from "// Initial injection - checks if dark mode is enabled." to "// Initial injection - gets the settings and apply them.". But it should probably be "// Initial injection - gets the settings and applies them."?

**Comment by aidanhorton** [comment]
Either of those is fine by me to be honest!

Apologies again - I keep saying this, but it's actually been the most hectic month of my life! I've got a trip this weekend, and am helping with moving house throughout next week, but will try and find some time to test this as I know it's been waiting for a while now!

Thanks for your patience 😊

**Comment by OppnedKatt** [comment]
I haven't really had that much time on my hands for while now either. I've had lots of things to finish up, and this next week will be quite bad when it comes to that. So no worries :)

**Comment by aidanhorton** [comment]
Just checked this over, and it all seems to be working great! Sorry it took so long, I'm hoping the turnaround time will be relatively fast going forwards, I don't want to let this project fade out, as it has lots of active users!
Thanks very much for all the work put into this @OppnedKatt, it's really great stuff!

**Pull request merged**
